# Generated by Django 4.2.6 on 2023-10-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_rename_registrationss_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='caddress',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
