# Generated by Django 5.0.1 on 2024-01-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.CharField(blank=True, help_text='Enter Youtube link without https. ex: www.youtube.com/xyz ', max_length=150, null=True)),
                ('linkedin_link', models.CharField(blank=True, help_text='Enter Linkedin link without https. ex: www.linkedin.com/xyz ', max_length=150, null=True)),
                ('twitter_link', models.CharField(blank=True, help_text='Enter Twitter link without https. ex: www.twitter.com/xyz ', max_length=150, null=True)),
                ('facebook_link', models.CharField(blank=True, help_text='Enter Facebook link without https. ex: www.facebook.com/xyz ', max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Social Media Profile Links',
            },
        ),
        migrations.CreateModel(
            name='WebsiteProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Enter Phone Number with Country Code.', max_length=12)),
                ('email', models.CharField(help_text='Email of the Company', max_length=10)),
                ('company_address', models.CharField(help_text='Enter Address that you want to show in footer. ', max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Website Profle Info',
            },
        ),
    ]
