# Generated by Django 5.0.1 on 2024-01-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProfileInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteprofiledata',
            name='email',
            field=models.CharField(help_text='Email of the Company', max_length=150),
        ),
    ]
