# Generated by Django 5.0.1 on 2024-01-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebsiteProfileInfo', '0002_alter_websiteprofiledata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteprofiledata',
            name='phone',
            field=models.CharField(help_text='Enter Phone Number with Country Code.', max_length=13),
        ),
    ]
