# Generated by Django 4.2.6 on 2023-10-18 07:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain_Registration_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='<150 Chars', max_length=150)),
                ('sub_heading', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Graphic_Design_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='<150 Chars', max_length=150)),
                ('sub_heading', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Web_Design_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='<150 Chars', max_length=150)),
                ('sub_heading', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Web_Hosting_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='<150 Chars', max_length=150)),
                ('sub_heading', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Web_Marketing_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='<150 Chars', max_length=150)),
                ('sub_heading', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Web_Services_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Graphic_Design_Heading', models.CharField(max_length=150)),
                ('Graphic_Design_Description', tinymce.models.HTMLField()),
                ('Web_Design_Heading', tinymce.models.HTMLField()),
                ('Domain_Register_Heading', models.CharField(max_length=150)),
                ('Domain_Register_Description', tinymce.models.HTMLField()),
                ('Web_Hosting_Heading', models.CharField(max_length=150)),
                ('Web_Hosting_Description', tinymce.models.HTMLField()),
                ('Web_Marketing_Heading', models.CharField(max_length=150)),
                ('Web_Marketing_Description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Domain_Registration',
        ),
        migrations.DeleteModel(
            name='Graphic_Design',
        ),
        migrations.DeleteModel(
            name='Web_Design',
        ),
        migrations.DeleteModel(
            name='Web_Hosting',
        ),
        migrations.DeleteModel(
            name='Web_Marketing',
        ),
    ]
