# Generated by Django 4.2.6 on 2023-11-01 07:20

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0007_alter_graphic_design_card_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_Hosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_heading', models.CharField(help_text='Main Heading of the Page', max_length=50)),
                ('page_description', models.TextField(help_text='Description of the page. ')),
            ],
            options={
                'verbose_name_plural': 'Web Hosting',
            },
        ),
        migrations.CreateModel(
            name='Web_Hosting_Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(blank=True, help_text='Enter your Package name eg. Platinum, Gold or Basic,Advanced', max_length=50)),
                ('server', models.CharField(blank=True, help_text='Package offers Which Server eg.- linux,windows etc.', max_length=50)),
                ('package_description', tinymce.models.HTMLField(blank=True, max_length=250)),
                ('card', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web_services.web_hosting')),
            ],
            options={
                'verbose_name_plural': 'Web Hosting Features and Prices',
            },
        ),
        migrations.DeleteModel(
            name='Web_Hosting_Card',
        ),
    ]
