# Generated by Django 4.2.6 on 2023-11-01 07:59

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0009_graphic_design_graphic_design_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_heading', models.CharField(help_text='Main Heading of the Page', max_length=50)),
                ('page_description', models.TextField(help_text='Description of the page. ')),
            ],
            options={
                'verbose_name_plural': 'Web Design',
            },
        ),
        migrations.AlterModelOptions(
            name='graphic_design',
            options={'verbose_name_plural': 'Graphic Design'},
        ),
        migrations.CreateModel(
            name='Web_Design_Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(blank=True, help_text='Enter your Package name eg. Platinum, Gold or Basic,Advanced', max_length=50)),
                ('service', models.CharField(blank=True, help_text='Services tha you offers.. eg.- static, dynamic site, wordress etc.', max_length=50)),
                ('package_description', tinymce.models.HTMLField(blank=True, max_length=250)),
                ('card', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web_services.web_design')),
            ],
            options={
                'verbose_name_plural': 'Web Design Features and Prices',
            },
        ),
    ]
