# Generated by Django 4.2.7 on 2023-12-11 07:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0012_delete_domain_registration_card_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphic_design_box',
            options={'verbose_name_plural': 'Graphic Design Features and Prices'},
        ),
        migrations.AlterField(
            model_name='domain_register_box',
            name='package_description',
            field=tinymce.models.HTMLField(blank=True, help_text='more text may create problem in UI. ', max_length=350),
        ),
        migrations.AlterField(
            model_name='graphic_design_box',
            name='package_description',
            field=tinymce.models.HTMLField(blank=True, help_text='more text may create problem in UI. ', max_length=250),
        ),
        migrations.AlterField(
            model_name='web_design_box',
            name='package_description',
            field=tinymce.models.HTMLField(blank=True, help_text='Note - Only up to 8 Points allowed    ', max_length=350),
        ),
        migrations.AlterField(
            model_name='web_hosting_box',
            name='package_description',
            field=tinymce.models.HTMLField(blank=True, help_text='more text may create problem in UI. ', max_length=250),
        ),
        migrations.AlterField(
            model_name='web_marketing_box',
            name='package_description',
            field=tinymce.models.HTMLField(blank=True, help_text='more text may create problem in UI. '),
        ),
    ]
