# Generated by Django 4.2.7 on 2023-11-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='phone',
            new_name='mobileno',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
