# Generated by Django 4.2.3 on 2023-10-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_solutions', '0003_erp_education_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='automobile_Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_container_heading', models.TextField(blank=True, null=True)),
                ('card_title', models.CharField(max_length=100)),
                ('card_description', models.TextField()),
                ('card_icon_image', models.ImageField(upload_to='erp/automobile')),
            ],
        ),
        migrations.CreateModel(
            name='ERP_Finance_Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_container_heading', models.TextField(blank=True, null=True)),
                ('card_title', models.CharField(max_length=100)),
                ('card_description', models.TextField()),
                ('card_icon_image', models.ImageField(upload_to='erp/finance')),
            ],
        ),
        migrations.CreateModel(
            name='medical_and_healthcare_Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_container_heading', models.TextField(blank=True, null=True)),
                ('card_title', models.CharField(max_length=100)),
                ('card_description', models.TextField()),
                ('card_icon_image', models.ImageField(upload_to='erp/medical_and_healthcare')),
            ],
        ),
        migrations.CreateModel(
            name='services_Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_container_heading', models.TextField(blank=True, null=True)),
                ('card_title', models.CharField(max_length=100)),
                ('card_description', models.TextField()),
                ('card_icon_image', models.ImageField(upload_to='erp/services')),
            ],
        ),
        migrations.CreateModel(
            name='tours_and_travels_Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_container_heading', models.TextField(blank=True, null=True)),
                ('card_title', models.CharField(max_length=100)),
                ('card_description', models.TextField()),
                ('card_icon_image', models.ImageField(upload_to='erp/tours_and_travels')),
            ],
        ),
    ]
