# Generated by Django 4.2.3 on 2023-10-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_solutions', '0004_automobile_cards_erp_finance_cards_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ERP_Education_Cards',
            new_name='Education_Cards',
        ),
        migrations.RenameModel(
            old_name='ERP_Finance_Cards',
            new_name='Finance_Cards',
        ),
    ]
