# Generated by Django 4.2.6 on 2023-10-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_solutions', '0009_postimage_delete_add_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='card_description',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postimage',
            name='card_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
