# Generated by Django 4.2.6 on 2023-10-31 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_solutions', '0011_remove_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_heading', models.CharField(max_length=50)),
                ('page_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Services_box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_image', models.FileField(upload_to='erp_solutions/images')),
                ('box_heading', models.CharField(max_length=50)),
                ('box_description', models.CharField(max_length=250)),
                ('card', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='erp_solutions.services')),
            ],
        ),
    ]
