# Generated by Django 4.2.6 on 2023-10-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_solutions', '0012_services_services_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='page_description',
            field=models.TextField(),
        ),
    ]
