# Generated by Django 4.2.6 on 2023-10-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_solutions', '0013_alter_services_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='page_box_heading',
            field=models.CharField(default='null', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services_box',
            name='box_heading',
            field=models.CharField(help_text='Maximum Length 70 Chars.', max_length=70),
        ),
        migrations.AlterField(
            model_name='services_box',
            name='box_image',
            field=models.FileField(help_text='Make sure your all image have same dimensions and have no background for better Appearence.', upload_to='erp_solutions/images'),
        ),
    ]
