# Generated by Django 4.2.6 on 2023-11-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_solutions', '0019_medical_healthcare_medical_healthcare_box_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medical_and_healthcare_Cards',
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='education_box',
            options={'verbose_name_plural': 'Education Boxes'},
        ),
        migrations.AlterModelOptions(
            name='finance',
            options={'verbose_name_plural': 'Finance'},
        ),
        migrations.AlterModelOptions(
            name='finance_box',
            options={'verbose_name_plural': 'Finance Box'},
        ),
        migrations.AlterModelOptions(
            name='medical_healthcare',
            options={'verbose_name_plural': 'Medical & HealthCare'},
        ),
        migrations.AlterModelOptions(
            name='medical_healthcare_box',
            options={'verbose_name_plural': 'Medical & HealthCare Boxes'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Service'},
        ),
        migrations.AlterModelOptions(
            name='services_box',
            options={'verbose_name_plural': 'Services Box'},
        ),
        migrations.AlterModelOptions(
            name='tours_travels',
            options={'verbose_name_plural': 'Tours And Travels'},
        ),
        migrations.AlterModelOptions(
            name='tours_travels_box',
            options={'verbose_name_plural': 'Tours and Travel Box'},
        ),
    ]
