# Generated by Django 3.2.21 on 2023-09-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=40)),
                ('intrested_in', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('collage', models.CharField(max_length=50)),
            ],
        ),
    ]
