# Generated by Django 3.2.21 on 2023-09-22 07:50

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0005_six_weeks_intern'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hope_Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
    ]
