# Generated by Django 4.2.3 on 2023-09-28 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0012_rename_job_title_career_with_us_job_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career_with_us',
            old_name='main_title',
            new_name='job_title',
        ),
    ]
