# Generated by Django 4.2.3 on 2023-09-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0013_rename_main_title_career_with_us_job_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry_Data',
        ),
    ]
