# Generated by Django 4.2.3 on 2023-10-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0014_delete_enquiry_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=150)),
                ('paragraph', models.TextField()),
            ],
        ),
    ]
