# Generated by Django 4.2.3 on 2023-10-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0016_delete_education'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Career_With_Us',
        ),
        migrations.DeleteModel(
            name='Hope_Program',
        ),
        migrations.DeleteModel(
            name='Six_Weeks_Intern',
        ),
        migrations.DeleteModel(
            name='Tech_Descovery',
        ),
    ]
