# Generated by Django 4.2.6 on 2023-10-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0019_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Enter Phone Number of Cmpny', max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(help_text='Write in Less than 250 chars', max_length=250)),
                ('facebook_link', models.CharField(blank=True, max_length=250, null=True)),
                ('Instagram_link', models.CharField(blank=True, max_length=250, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=250, null=True)),
                ('linkdin_link', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
