# Generated by Django 4.2.6 on 2023-10-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0021_alter_website_details_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_details',
            name='youtube_link',
            field=models.CharField(blank=True, help_text='Important Note - link Must starts with https://', max_length=250, null=True),
        ),
    ]
