# Generated by Django 4.2.3 on 2023-09-28 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0009_rename_experience_required_career_with_us_experience_required_in_years'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career_with_us',
            old_name='location',
            new_name='city_location',
        ),
        migrations.RenameField(
            model_name='career_with_us',
            old_name='main_title',
            new_name='job_profile',
        ),
        migrations.RenameField(
            model_name='career_with_us',
            old_name='sub_title',
            new_name='job_title',
        ),
    ]
