# Generated by Django 4.2.3 on 2023-09-28 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0011_rename_job_profile_career_with_us_main_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career_with_us',
            old_name='job_title',
            new_name='job_profile',
        ),
    ]
