# Generated by Django 4.2.6 on 2023-10-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0018_delete_domain_registration_delete_graphic_design_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Enter Your Project Name ex. PisotInformatics', max_length=50)),
                ('project_link', models.CharField(blank=True, help_text='Enter domain name of Your Project. ex - www.xyz.com', max_length=250, null=True)),
                ('device', models.CharField(help_text='Only Choose one --> Mobile, Web or Desktop', max_length=50)),
                ('project_image', models.ImageField(upload_to='portfolio/')),
            ],
        ),
    ]
