# Generated by Django 4.2.6 on 2023-10-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0020_website_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website_details',
            name='Instagram_link',
            field=models.CharField(blank=True, help_text='Important Note - link Must starts with https://', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='website_details',
            name='facebook_link',
            field=models.CharField(blank=True, help_text='Important Note - link Must starts with https://', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='website_details',
            name='linkdin_link',
            field=models.CharField(blank=True, help_text='Important Note - link Must starts with https://', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='website_details',
            name='phone',
            field=models.CharField(help_text='Enter Phone Number of Cmpny without +91', max_length=12),
        ),
        migrations.AlterField(
            model_name='website_details',
            name='twitter_link',
            field=models.CharField(blank=True, help_text='Important Note - link Must starts with https://', max_length=250, null=True),
        ),
    ]
