# Generated by Django 4.2.6 on 2023-10-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0022_website_details_youtube_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website_Details',
        ),
    ]
