# Generated by Django 4.2.6 on 2023-11-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0026_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage_recent_project_data',
            options={'verbose_name_plural': 'Recent Project'},
        ),
    ]
