# Generated by Django 4.2.7 on 2023-11-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0027_alter_homepage_recent_project_data_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage_recent_project_data',
            options={'verbose_name_plural': 'Recent Project of Home Page'},
        ),
    ]
