# Generated by Django 4.2.7 on 2023-12-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0028_alter_homepage_recent_project_data_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VTabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Vertical Tabs',
            },
        ),
    ]
