# Generated by Django 4.2.7 on 2023-12-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0029_vtabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtabs',
            name='text',
            field=models.TextField(help_text='maximum length is 70 words', max_length=70),
        ),
    ]
