# Generated by Django 4.2.7 on 2023-12-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0030_alter_vtabs_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtabs',
            name='text',
            field=models.TextField(help_text='maximum length is 450 Characters words', max_length=450),
        ),
    ]
