# Generated by Django 5.0.1 on 2024-01-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0033_alter_portfolio_project_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VTabs',
        ),
    ]
