# Generated by Django 4.2.6 on 2023-10-16 09:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('career_and_intern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career_with_us',
            name='job_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
