# Generated by Django 5.0.1 on 2024-01-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_and_intern', '0003_alter_career_with_us_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traniee_with_us',
            name='trainee_image',
            field=models.ImageField(blank=True, default='static/img/no-image.jpg', upload_to='career_and_intern/trainee_with_us'),
        ),
    ]
