# Generated by Django 4.2.7 on 2023-11-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('position_applied_for', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=90)),
                ('address', models.TextField()),
                ('remarks', models.TextField()),
                ('skills', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('experience', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='career_and_intern/apply_job/resumes')),
            ],
            options={
                'verbose_name_plural': 'Apply Job',
            },
        ),
        migrations.CreateModel(
            name='Contact_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact form Data',
            },
        ),
        migrations.CreateModel(
            name='HEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('intrested_in', models.CharField(max_length=70)),
                ('education', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
                ('module_price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Modules',
                'db_table': 'modules',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('caddress', models.CharField(blank=True, max_length=50, null=True)),
                ('module', models.CharField(max_length=50)),
                ('pursuing_details', models.CharField(max_length=50)),
                ('training_program', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Registrations',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobileno', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
    ]
