# Generated by Django 4.2.7 on 2023-11-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('icon', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('path', models.CharField(max_length=250)),
                ('priority', models.IntegerField()),
                ('parent_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Header',
                'db_table': 'header',
            },
        ),
    ]
