# Generated by Django 4.2.7 on 2023-11-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='header',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='header',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.header'),
        ),
        migrations.AlterField(
            model_name='header',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ChildHeader',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('path', models.CharField(max_length=250)),
                ('priority', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='records.header')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
