# Generated by Django 4.2.7 on 2023-11-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_remove_header_p_id_remove_header_parent_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childheader',
            options={'ordering': ['priority'], 'verbose_name_plural': 'childHeader'},
        ),
        migrations.AlterModelTable(
            name='childheader',
            table='childHeader',
        ),
    ]
