# Generated by Django 4.2.7 on 2023-11-24 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_childheader_options_alter_childheader_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildHeaderr',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('path', models.CharField(max_length=250)),
                ('priority', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='records.header')),
            ],
            options={
                'verbose_name_plural': 'childHeader',
                'db_table': 'childHeader',
                'ordering': ['priority'],
            },
        ),
        migrations.DeleteModel(
            name='ChildHeader',
        ),
    ]
