# Generated by Django 4.2.7 on 2023-11-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_alter_childheaders_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childheaders',
            options={'ordering': ['priority'], 'verbose_name_plural': 'db_childHeader'},
        ),
    ]
