# Generated by Django 4.2.7 on 2023-11-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_alter_childheader_options_alter_header_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childheader',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='records.header'),
        ),
    ]
