# Generated by Django 4.2.7 on 2023-11-25 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_alter_header_options_remove_header_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.header'),
        ),
        migrations.DeleteModel(
            name='Children',
        ),
    ]
