# Generated by Django 4.2.7 on 2023-11-25 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_rename_priority_header_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Header',
        ),
    ]
