# Generated by Django 4.2.7 on 2023-12-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0022_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254)),
                ('module', models.CharField(max_length=50)),
                ('header_ids', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Intrested in Demo',
                'db_table': 'free_demo',
            },
        ),
    ]
