# Generated by Django 4.2.6 on 2023-11-01 07:44

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0008_web_hosting_web_hosting_box_delete_web_hosting_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphic_Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_heading', models.CharField(help_text='Main Heading of the Page', max_length=50)),
                ('page_description', models.TextField(help_text='Description of the page. ')),
            ],
            options={
                'verbose_name_plural': 'Web Hosting',
            },
        ),
        migrations.CreateModel(
            name='Graphic_Design_Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, help_text='Services tha you offers.. eg.- logo,stationary etc.', max_length=50)),
                ('package', models.CharField(blank=True, help_text='Enter your Package name eg. Platinum, Gold or Basic,Advanced', max_length=50)),
                ('package_description', tinymce.models.HTMLField(blank=True, max_length=250)),
                ('card', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web_services.graphic_design')),
            ],
            options={
                'verbose_name_plural': 'Graphic_Design Features and Prices',
            },
        ),
    ]
