# Generated by Django 4.2.6 on 2023-10-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_rename_registration_registrations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrationss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('caddress', models.CharField(max_length=50)),
                ('module', models.CharField(max_length=50)),
                ('pursuing_details', models.CharField(max_length=50)),
                ('training_program', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Registrations',
        ),
    ]
