# Generated by Django 4.2.6 on 2023-10-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_rename_collage_henquiry_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_data',
            name='phone',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
