# Generated by Django 4.2.6 on 2023-11-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_contact_data_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apply_job',
            options={'verbose_name_plural': 'Apply Job'},
        ),
        migrations.AlterModelOptions(
            name='contact_data',
            options={'verbose_name_plural': 'Contact form Data'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name_plural': 'Registrations'},
        ),
    ]
