# Generated by Django 5.0.1 on 2024-01-16 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_contact_data_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254)),
                ('module', models.CharField(max_length=50)),
                ('header_ids', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Intrested in Free Demo',
                'db_table': 'free_demo',
            },
        ),
        migrations.CreateModel(
            name='modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
                ('module_price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Modules',
                'db_table': 'modules',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobileno', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
        migrations.AlterModelOptions(
            name='apply_job',
            options={'verbose_name_plural': 'Apply Job'},
        ),
        migrations.AlterModelOptions(
            name='contact_data',
            options={'verbose_name_plural': 'Contact form Data'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name_plural': 'Registrations'},
        ),
        migrations.RenameField(
            model_name='henquiry',
            old_name='college',
            new_name='collage',
        ),
        migrations.RenameField(
            model_name='henquiry',
            old_name='intrested_in',
            new_name='interested_in',
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('path', models.CharField(max_length=250)),
                ('priority', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='records.header')),
            ],
            options={
                'verbose_name_plural': 'Headers',
                'db_table': 'header',
            },
        ),
    ]
