# Generated by Django 5.0.1 on 2024-01-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_delete_demo_data_remove_header_parent_delete_modules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
                ('module_price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Modules',
            },
        ),
    ]
