# Generated by Django 4.2.3 on 2023-09-28 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0008_desktop_applications_mobile_applications_web_applications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career_with_us',
            old_name='experience_required',
            new_name='experience_required_in_years',
        ),
    ]
