# Generated by Django 4.2.3 on 2023-09-28 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0010_rename_location_career_with_us_city_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career_with_us',
            old_name='job_profile',
            new_name='main_title',
        ),
    ]
