# Generated by Django 4.2.3 on 2023-10-13 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bossapp', '0015_education'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
