# Generated by Django 4.2.7 on 2023-11-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwaredev', '0002_alter_desktop_applications_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
                ('module_price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Modules',
                'db_table': 'modules',
            },
        ),
    ]
