# Generated by Django 4.2.6 on 2023-10-31 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_solutions', '0005_rename_erp_education_cards_education_cards_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education_cards',
            options={'verbose_name': 'Cards | Educations'},
        ),
        migrations.AlterModelOptions(
            name='erp_solutions_header',
            options={'verbose_name': 'Header | ERP Solutions'},
        ),
        migrations.AlterModelOptions(
            name='finance_cards',
            options={'verbose_name': 'Cards | Finance '},
        ),
        migrations.AlterModelOptions(
            name='medical_and_healthcare_cards',
            options={'verbose_name': 'Cards | Medical & Healtcare'},
        ),
        migrations.AlterModelOptions(
            name='services_cards',
            options={'verbose_name': 'Cards | Services'},
        ),
        migrations.AlterModelOptions(
            name='tours_and_travels_cards',
            options={'verbose_name': 'Cards | Tours & Travels'},
        ),
        migrations.AddField(
            model_name='services_cards',
            name='Service_Heading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_solutions.erp_solutions_header'),
        ),
    ]
