# Generated by Django 4.2.6 on 2023-11-01 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_solutions', '0018_finance_finance_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Healthcare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_heading', models.CharField(max_length=50)),
                ('page_description', models.TextField()),
                ('heading_for_box_section', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Healthcare_Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_image', models.FileField(blank=True, help_text='Make sure your all image have same dimensions and have no background for better Appearence.', upload_to='erp_solutions/images')),
                ('box_heading', models.CharField(blank=True, help_text='Maximum Length 70 Chars.', max_length=70)),
                ('box_description', models.CharField(blank=True, max_length=250)),
                ('card', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='erp_solutions.medical_healthcare')),
            ],
        ),
        migrations.DeleteModel(
            name='automobile_Cards',
        ),
        migrations.DeleteModel(
            name='Education_Cards',
        ),
        migrations.DeleteModel(
            name='Finance_Cards',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='services_cards',
            name='Service_Heading',
        ),
        migrations.DeleteModel(
            name='tours_and_travels_Cards',
        ),
        migrations.DeleteModel(
            name='ERP_Solutions_Header',
        ),
        migrations.DeleteModel(
            name='services_Cards',
        ),
    ]
