# Generated by Django 4.2.3 on 2023-10-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erp_solutions_header',
            name='finance_page_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='erp_solutions_header',
            name='finance_page_heading',
            field=models.TextField(max_length=300),
        ),
    ]
