# Generated by Django 4.2.3 on 2023-10-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_solutions', '0002_erp_solutions_header_finance_page_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERP_Education_Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_container_heading', models.TextField(blank=True, null=True)),
                ('card_title', models.CharField(max_length=100)),
                ('card_description', models.TextField()),
                ('card_icon_image', models.ImageField(upload_to='erp/education')),
            ],
        ),
    ]
