# Generated by Django 4.2.6 on 2023-10-18 10:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_services', '0006_alter_domain_registration_card_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic_design_card',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='graphic_design_card',
            name='heading',
            field=models.CharField(blank=True, default='', help_text='<150 Chars', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='graphic_design_card',
            name='sub_heading',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='web_design_card',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='web_design_card',
            name='heading',
            field=models.CharField(blank=True, default='', help_text='<150 Chars', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='web_design_card',
            name='sub_heading',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='web_hosting_card',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='web_hosting_card',
            name='heading',
            field=models.CharField(blank=True, default='', help_text='<150 Chars', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='web_hosting_card',
            name='sub_heading',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='web_marketing_card',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='web_marketing_card',
            name='heading',
            field=models.CharField(blank=True, default='', help_text='<150 Chars', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='web_marketing_card',
            name='sub_heading',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
