# Generated by Django 4.2.6 on 2023-10-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Registrations',
        ),
        migrations.RenameField(
            model_name='registrations',
            old_name='fathername',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='registrations',
            old_name='payment',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='registrations',
            old_name='pursuingdetails',
            new_name='pursuing_details',
        ),
        migrations.RenameField(
            model_name='registrations',
            old_name='trainingprogram',
            new_name='training_program',
        ),
    ]
