# Generated by Django 4.2.6 on 2023-10-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_registrationss_delete_registrations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrationss',
            new_name='Registration',
        ),
    ]
