# Generated by Django 4.2.7 on 2023-11-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_rename_childheader_childheaders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChildHeaders',
        ),
    ]
