# Generated by Django 4.2.7 on 2023-11-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_childheaders'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='childheaders',
            table='db_childHeader',
        ),
    ]
