# Generated by Django 4.2.7 on 2023-11-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_modules_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
