# Generated by Django 4.2.7 on 2023-11-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_homie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homie',
        ),
    ]
