# Generated by Django 4.2.7 on 2023-11-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_alter_childheader_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name_plural': 'Header'},
        ),
        migrations.AlterModelTable(
            name='header',
            table='header',
        ),
    ]
