# Generated by Django 4.2.7 on 2023-11-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_alter_header_priority_delete_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='priority',
            new_name='parent',
        ),
    ]
