# Generated by Django 4.2.6 on 2023-11-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_alter_chandigarh_web_website_domain_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chandigarh_web',
            options={'verbose_name_plural': 'Chandigarh Web'},
        ),
        migrations.AlterModelOptions(
            name='class_ikart',
            options={'verbose_name_plural': 'Class ikart'},
        ),
        migrations.AlterModelOptions(
            name='elive_today',
            options={'verbose_name_plural': 'Elive Today'},
        ),
    ]
