# Generated by Django 4.2.6 on 2023-11-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softwaredev', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desktop_applications',
            options={'verbose_name_plural': 'Desktop Application'},
        ),
        migrations.AlterModelOptions(
            name='mobile_applications',
            options={'verbose_name_plural': 'Mobile Application'},
        ),
        migrations.AlterModelOptions(
            name='web_applications',
            options={'verbose_name_plural': 'Web Application'},
        ),
    ]
