# Generated by Django 4.2.7 on 2023-11-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softwaredev', '0003_modules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='modules',
        ),
    ]
