# Generated by Django 4.2.6 on 2023-10-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chandigarh_web',
            name='website_domain_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='class_ikart',
            name='website_domain_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='elive_today',
            name='website_domain_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
